# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm.fullname" . }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
data:
  config.yaml: |
    model_list:
{{- if .Values.modelList }}
{{ toYaml .Values.modelList | indent 6 }}
{{- else }}
      []
{{- end }}
    general_settings:
{{- if .Values.generalSettings }}
{{ toYaml .Values.generalSettings | indent 6 }}
{{- else }}
      {}
{{- end }}
    litellm_settings:
{{ toYaml (mergeOverwrite (dict "drop_params" true "set_verbose" false "callbacks" (list "litellm.proxy.hooks.apim_key_hook.proxy_handler_instance")) .Values.litellmSettings) | indent 6 }}
