# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
type: Opaque
stringData:
  master_key: {{ required "secrets.masterKey is required" .Values.secrets.masterKey | quote }}
  database_url: {{ required "secrets.databaseUrl is required" .Values.secrets.databaseUrl | quote }}
