# SPDX-FileCopyrightText: Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: agent-sandbox-system
  labels:
    app.kubernetes.io/part-of: agent-sandbox
